apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.projectname }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        nl.duo.networkpolicy.allow-ingress: "true"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            #- name: nginx-config-volume
            #  mountPath: /etc/nginx/nginx.conf
            - name: nginx-default-volume
              mountPath: /etc/nginx/conf.d/
          ports:
            - containerPort: {{ .Values.image.port }}
              name: container-port
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
            items:
              - key: mime.types
                path: mime.types
              - key: nginx.conf
                path: nginx.conf
        - name: nginx-default-volume
          configMap:
            name: nginx-config
            items:
              - key: default.conf
                path: default.conf
