kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: {{ .Values.projectname }}
data:
  default.conf: |

    server {
      listen {{ .Values.image.port }} default_server;
      server_name _;
      root /usr/share/nginx/html;

      # Add security headers
      add_header X-Frame-Options SAMEORIGIN always;
      add_header X-Content-Type-Options nosniff always;
      add_header X-XSS-Protection "1; mode=block" always;
      add_header Content-Security-Policy "default-src 'self' https://google.com https://fonts.google.com https://fonts.googleapis.com https://ajax.googleapis.com https://www.google-analytics.com; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; font-src 'self'; object-src 'none'; media-src 'self'; form-action 'self'; frame-ancestors 'self';" always;

      error_page 404 /404.html;
      error_page 500 501 502 503 504 /50x.html;
    }
