kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Release.Name }}-route
  namespace: {{ .Values.projectname }}
spec:
  to:
    kind: Service
    name: vue-welcome-app-svc
    weight: 100
  port:
    targetPort: {{ .Release.Name }}-svc-port
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
